name: production_merge_action
on:
    schedule:
    - cron: '5 * * * *'
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was auto triggered by a ${{ github.event_name }} event"
    create_pull_request:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Just checking things out"
