name: production-merge-action
run-name: Production Merge 
on: workflow_dispatch
#on:
#    schedule:
#    - cron: '48 * * * *'
jobs:
    create-production-merge:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: get current date
              id: date
              run: |
                echo "{date}={$(date +'%Y-%m-%d')}" >> "$GITHUB_ENV"
            - run: echo "$date"
            - name: create pull request
              run: gh pr create -B production_testing -H develop --title "[Production Merge] ${env:date}" --body 'Created by Github Actions'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: echo "The job was auto triggered by a schedule"

