name: production_merge_action
run-name: ${{ github.actor }} is creating the production merge
on:
    schedule:
        - cron: '5 * * * *'
jobs:
    create_pull_request:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Just checking things out"
